### PR TITLE
Allow passing custom repository to cli.Dockerfile through build-chain.sh

### PR DESCRIPTION
**Pull request by piotrpio**

### CODE REVIEW

**Comment by lukaszczerpak** [comment]
The changes look good. I am merging them to dev branch in order to run full build and validate all works fine in travis as well. Once it's done w/o any errors I will approve.

**Review by lukaszczerpak — APPROVED** [review]
LGTM

**Review by ynohat — CHANGES_REQUESTED** [review]
@piotrpio this looks good in general. Rather than change the number of args build-chain.sh can take, could we consider introducing a new env var in env.sh (DOCKER_BUILD_EXTRA_ARGS) ?

You'd invoke the build with e.g.

DOCKER_BUILD_EXTRA_ARGS="--build-arg CLI_REPOSITORY_URL=http://localhost:1234"

This would be better IMO because:

* logic in build-chain.sh is easier to parse - just append DOCKER_BUILD_EXTRA_ARGS to docker command
* build args apply to the entire build and are not coupled to a specific variant; if a Dockerfile uses a build arg, then it will get it, regardless of the variant; this means that the variant name prefix is just a useful naming convention
* it may be useful to pass other arguments to docker in other use cases

what do you think?

**Comment by piotrpio** [comment]
Thanks for the suggestion, I agree. PR is updated.

**Comment by lukaszczerpak** [comment]
The build completed on the dev branch.

**Review by ynohat — APPROVED** [review]

**Pull request merged**
