### PR TITLE
Feature/cli eaa

### PR DESCRIPTION
**Pull request by lukaszczerpak**
The new variant was verified and is ready to be released.

### CODE REVIEW

**Review by ynohat — APPROVED** [review]
LGTM!
Only concern is the extra merge commits in the history; can we enforce a rebase and strict fast-forward merge policy on feature branches? This is not blocking this PR.

**Comment by lukaszczerpak** [comment]
> Only concern is the extra merge commits in the history; can we enforce a rebase and strict fast-forward merge policy on feature branches? This is not blocking this PR.

Fixed. Thanks for the review!

**Review by javiergarza — APPROVED** [review]
LGTM, thanks Lukasz!

**Comment by akamaimike** [comment]
LGTM as well! Thanks for adding CLI EAA.

**Review by akamaimike — APPROVED** [review]
LGTM!

**Pull request merged**
