### PR TITLE
update dockerfiles for CLI 1.4.0

### PR DESCRIPTION
**Pull request by robertolopezlopez**
* I thought I would have to add some new system dependencies, it turned out that this was not necessary
* Instead of installing those new dependencies globally, I installed them within a virtual environment (this is what CLI 1.4.0 will use)
* I reconfigured logging (to a specific location, defined in cli.Dockerfile).
* Some extra cleanup: visitor-prioritization and property dockerfiles were to be deleted soon, so I have done it already. (See [this](https://track.akamai.com/jira/browse/DXE-724) and [this](https://track.akamai.com/jira/browse/DXE-710) ticket). I hope I have not forgotten any detail.

### CODE REVIEW

**Comment by robertolopezlopez** [comment]
@ynohat : changes of this PR have been [cherry-picked and pushed to dev](https://github.com/akamai/akamai-docker/commit/81d1442ec2c54e870e009df6310d8e76e3f94920)

**Comment by robertolopezlopez** [comment]
We were able finally to trigger the build from dev branch

https://app.travis-ci.com/github/akamai/akamai-docker/builds/250162086

I am not sure though why cli-terraform has failed, because I didn't touch this at all.

**Review by lkowalsk-akamai-com — APPROVED** [review]

**Review by securitylevelup — APPROVED** [review]
Approved!

**Comment by robertolopezlopez** [comment]
Build is green now https://app.travis-ci.com/github/akamai/akamai-docker/builds/250201285

**Pull request merged**
